### ISSUE TITLE
FE OPTION 4 - Client side Validation: Edit Merchant

### ISSUE THREAD

**Issue by kylomite** [Sgalvin36/little_shop#68]
- Add client-side validation to ensure we aren’t doing the PATCH request unless we’ve confirmed that a change has actually been made to the merchant name and that the merchant’s edited name field isn’t blank.

**Comment by Sgalvin36** [comment]
Modified createMerchant to check if the value is empty before proceeding with rest of logic. If its empty returns a status of no name being provided.
